// GERADO por scripts/gerar-indice-do-catecismo.ts — não editar à mão.
//
// A estrutura do Catecismo da Igreja Católica, na ordem do livro: cada
// linha é [nível, parágrafo em que começa, rótulo, título, âncora na página].
// Os títulos são do texto oficial em português publicado em vatican.va
// (tradução de Portugal), passados de maiúsculas para frase.

export type NivelDoCatecismo = "parte" | "subtitulo" | "topico" | "secao" | "capitulo" | "artigo" | "paragrafo";

export type LinhaDoIndice = readonly [NivelDoCatecismo, number, string, string, string?];

/** [primeiro parágrafo, último parágrafo, arquivo] — uma página por capítulo. */
export const PAGINAS_DO_CATECISMO: readonly (readonly [number, number, string])[] = [
  [1, 25, "prologo 1-25_po.html"],
  [26, 49, "p1s1c1_26-49_po.html"],
  [50, 141, "p1s1c2_50-141_po.html"],
  [142, 184, "p1s1c3_142-184_po.html"],
  [185, 197, "p1s2_185-197_po.html"],
  [198, 421, "p1s2c1_198-421_po.html"],
  [422, 682, "p1s2cap2_422-682_po.html"],
  [683, 1065, "p1s2cap3_683-1065_po.html"],
  [1066, 1075, "p2s1cap1_1066-1075_po.html"],
  [1076, 1134, "p2s1cap1_1076-1134_po.html"],
  [1135, 1209, "p2s1cap2_1135-1209_po.html"],
  [1210, 1419, "p2s2cap1_1210-1419_po.html"],
  [1420, 1532, "p2s2cap1_1420-1532_po.html"],
  [1533, 1666, "p2s2cap3_1533-1666_po.html"],
  [1667, 1690, "p2s2cap4_1667-1690_po.html"],
  [1691, 1698, "p3-intr_1691-1698_po.html"],
  [1699, 1876, "p3s1cap1_1699-1876_po.html"],
  [1877, 1948, "p3s1cap2_1877-1948_po.html"],
  [1949, 2051, "p3s1cap3_1949-2051_po.html"],
  [2052, 2082, "p3s2-intr_2052-2082_po.html"],
  [2083, 2195, "p3s2cap1_2083-2195_po.html"],
  [2196, 2557, "p3s2cap2_2196-2557_po.html"],
  [2558, 2565, "p4-intr_2558-2565_po.html"],
  [2566, 2649, "p4s1cap1_2566-2649_po.html"],
  [2650, 2696, "p4s1cap2_2650-2696_po.html"],
  [2697, 2758, "p4s1cap3_2697-2758_po.html"],
  [2759, 2865, "p4s2_2759-2865_po.html"],
];

export const INDICE_DO_CATECISMO: readonly LinhaDoIndice[] = [
  ["parte",1,"","Prólogo"],
  ["subtitulo",1,"I","A vida do homem – conhecer e amar a Deus"],
  ["subtitulo",4,"II","Transmitir a fé – a catequese"],
  ["subtitulo",11,"III","Finalidade e destinatários deste catecismo"],
  ["subtitulo",13,"IV","Estrutura deste catecismo"],
  ["subtitulo",18,"V","Indicações práticas para o uso deste catecismo"],
  ["subtitulo",23,"VI","Adaptações necessárias"],
  ["topico",25,"","Acima de tudo — a caridade"],
  ["parte",26,"Parte 1","A profissão da fé"],
  ["secao",26,"Seção 1","«Eu creio» – «nós cremos»"],
  ["capitulo",27,"Capítulo 1","O homem é «capaz» de Deus"],
  ["subtitulo",27,"I","O desejo de Deus"],
  ["subtitulo",31,"II","Os caminhos de acesso ao conhecimento de Deus"],
  ["subtitulo",36,"III","O conhecimento de Deus segundo a Igreja"],
  ["subtitulo",39,"IV","Como falar de Deus?"],
  ["subtitulo",44,"","Resumindo"],
  ["capitulo",50,"Capítulo 2","Deus ao encontro do homem"],
  ["artigo",51,"Artigo 1","A revelação de Deus","ARTIGO_1_"],
  ["subtitulo",51,"I","Deus revela o seu «desígnio benevolente»"],
  ["subtitulo",54,"II","As etapas da Revelação"],
  ["topico",54,"","Desde a origem, Deus dá-se a conhecer"],
  ["topico",56,"","A aliança com Noé"],
  ["topico",59,"","Deus elege Abraão"],
  ["topico",62,"","Deus forma o seu povo Israel"],
  ["subtitulo",65,"III","Jesus Cristo – «Mediador e plenitude de toda a Revelação»"],
  ["topico",65,"","No seu Verbo, Deus disse tudo"],
  ["topico",66,"","Já não haverá outra revelação"],
  ["subtitulo",68,"","Resumindo"],
  ["artigo",74,"Artigo 2","A transmissão da revelação divina","ARTIGO_2_"],
  ["subtitulo",75,"I","A Tradição apostólica"],
  ["topico",76,"","A pregação apostólica ..."],
  ["topico",77,"","... continuada na sucessão apostólica"],
  ["subtitulo",80,"II","A relação entre a Tradição e a Sagrada Escritura"],
  ["topico",80,"","Uma fonte comum..."],
  ["topico",81,"","... duas formas de transmissão distintas"],
  ["topico",83,"","Tradição apostólica e tradições eclesiais"],
  ["subtitulo",84,"III","A interpretação da herança da fé"],
  ["topico",84,"","A herança da fé confiada à totalidade da Igreja"],
  ["topico",85,"","O Magistério da Igreja"],
  ["topico",88,"","Os dogmas da fé"],
  ["topico",91,"","O sentido sobrenatural da fé"],
  ["topico",94,"","O crescimento na inteligência da fé"],
  ["subtitulo",96,"","Resumindo"],
  ["artigo",101,"Artigo 3","A Sagrada Escritura","ARTIGO_3_"],
  ["subtitulo",101,"I","Cristo – Palavra única da Escritura santa"],
  ["subtitulo",105,"II","Inspiração e verdade da Sagrada Escritura"],
  ["subtitulo",109,"III","O Espírito Santo, intérprete da Escritura"],
  ["topico",115,"","Os sentidos da Escritura"],
  ["subtitulo",120,"IV","O Cânon das Escrituras"],
  ["topico",121,"","O Antigo Testamento"],
  ["topico",124,"","O Novo Testamento"],
  ["topico",128,"","A unidade do antigo e do Novo Testamento"],
  ["subtitulo",131,"V","A Sagrada Escritura na vida da Igreja"],
  ["subtitulo",134,"","Resumindo"],
  ["capitulo",142,"Capítulo 3","A resposta do homem a Deus"],
  ["artigo",144,"Artigo 1","Eu creio","ARTIGO_1_"],
  ["subtitulo",144,"I","A «obediência da fé»"],
  ["topico",145,"","Abraão – «o Pai de todos os crentes»"],
  ["topico",148,"","Maria – «feliz aquela que acreditou»"],
  ["subtitulo",150,"II","«Eu sei em quem pus a minha fé» (2 Tm 1, 12)"],
  ["topico",150,"","Crer só em Deus"],
  ["topico",151,"","Crer em Jesus Cristo, Filho de Deus"],
  ["topico",152,"","Crer no Espírito Santo"],
  ["subtitulo",153,"III","As características da fé"],
  ["topico",153,"","A fé é uma graça"],
  ["topico",154,"","A fé é um acto humano"],
  ["topico",156,"","A fé e a inteligência"],
  ["topico",160,"","A liberdade da fé"],
  ["topico",161,"","A necessidade da fé"],
  ["topico",162,"","A perseverança na fé"],
  ["topico",163,"","A fé – vida eterna iniciada"],
  ["artigo",166,"Artigo 2","Nós cremos","ARTIGO_2_"],
  ["subtitulo",168,"I","«Olhai, Senhor, para a fé da vossa Igreja»"],
  ["subtitulo",170,"II","A linguagem da fé"],
  ["subtitulo",172,"III","Uma só fé"],
  ["subtitulo",176,"","Resumindo"],
  ["secao",185,"Seção 2","A profissão da fé cristã"],
  ["topico",185,"","Os símbolos da fé"],
  ["capitulo",198,"Capítulo 1","Creio em Deus Pai"],
  ["artigo",199,"Artigo 1","«Creio em Deus Pai Todo-Poderoso Criador do céu e da terra»","ARTIGO_1_"],
  ["paragrafo",199,"Parágrafo 1","Creio em Deus"],
  ["subtitulo",200,"I","«Creio em um só Deus»"],
  ["subtitulo",203,"II","Deus revela o seu nome"],
  ["topico",205,"","O Deus vivo"],
  ["topico",206,"","«Eu sou aquele que sou»"],
  ["topico",210,"","«Deus de ternura e de piedade»"],
  ["topico",212,"","Só Deus é"],
  ["subtitulo",214,"III","Deus, «Aquele que é», é verdade e amor"],
  ["topico",215,"","Deus é a verdade"],
  ["topico",218,"","Deus é amor"],
  ["subtitulo",222,"IV","Consequências da fé no Deus Único"],
  ["subtitulo",228,"","Resumindo"],
  ["paragrafo",232,"Parágrafo 2","O Pai"],
  ["subtitulo",232,"I","«Em nome do Pai e do Filho e do Espírito Santo»"],
  ["subtitulo",238,"II","A revelação de Deus como Trindade"],
  ["topico",238,"","O Pai revelado pelo Filho"],
  ["topico",243,"","O Pai e o Filho revelados pelo Espírito"],
  ["subtitulo",249,"III","A Santíssima Trindade na doutrina da fé"],
  ["topico",249,"","A formação do dogma trinitário"],
  ["topico",253,"","O dogma da Santíssima Trindade"],
  ["subtitulo",257,"IV","As obras divinas e as missões trinitárias"],
  ["subtitulo",261,"","Resumindo"],
  ["paragrafo",268,"Parágrafo 3","O Todo-Poderoso"],
  ["topico",269,"","«Faz tudo quanto lhe apraz» (Sl 115, 3)"],
  ["topico",270,"","«Porque podeis tudo, de todos vos compadeceis» (Sb 11, 23)"],
  ["topico",272,"","O mistério da aparente impotência de Deus"],
  ["subtitulo",275,"","Resumindo"],
  ["paragrafo",279,"Parágrafo 4","O Criador"],
  ["subtitulo",282,"I","A catequese sobre a criação"],
  ["subtitulo",290,"II","A criação – obra da Santíssima Trindade"],
  ["subtitulo",293,"III","«O mundo foi criado para glória de Deus»"],
  ["subtitulo",295,"IV","O mistério da criação"],
  ["topico",295,"","Deus cria com sabedoria e por amor"],
  ["topico",296,"","Deus cria «do nada»"],
  ["topico",299,"","Deus cria um mundo ordenado e bom"],
  ["topico",300,"","Deus transcende a criação e está presente nela"],
  ["topico",301,"","Deus sustenta e conduz a criação"],
  ["subtitulo",302,"V","Deus realiza o seu desígnio: a divina Providência"],
  ["topico",306,"","A providência e as causas segundas"],
  ["topico",309,"","A providência e o escândalo do mal"],
  ["subtitulo",315,"","Resumindo"],
  ["paragrafo",325,"Parágrafo 5","Céu e a terra"],
  ["subtitulo",328,"I","Os anjos"],
  ["topico",328,"","A existência dos anjos uma verdade de fé"],
  ["topico",329,"","Quem são os anjos?"],
  ["topico",331,"","Cristo «com todos os seus anjos»"],
  ["topico",334,"","Os anjos na vida da Igreja"],
  ["subtitulo",337,"II","O mundo visível"],
  ["subtitulo",350,"","Resumindo"],
  ["paragrafo",355,"Parágrafo 6","O homem"],
  ["subtitulo",356,"I","«A imagem de Deus»"],
  ["subtitulo",362,"II","«Corpore et anima unus» – Unidade de corpo e alma"],
  ["subtitulo",369,"III","«Homem e mulher os criou»"],
  ["topico",369,"","Igualdade e diferença queridas por Deus"],
  ["topico",371,"","«Um para o outro» – «uma unidade a dois»"],
  ["subtitulo",374,"IV","O homem no paraíso"],
  ["subtitulo",380,"","Resumindo"],
  ["paragrafo",385,"Parágrafo 7","A queda"],
  ["subtitulo",386,"I","«Onde abundou o pecado, sobreabundou a graça»"],
  ["topico",386,"","A realidade do pecado"],
  ["topico",388,"","O pecado original – uma verdade fundamental da fé"],
  ["topico",390,"","Para ler a narrativa da queda"],
  ["subtitulo",391,"II","A queda dos anjos"],
  ["subtitulo",396,"III","O pecado original"],
  ["topico",396,"","A prova da liberdade"],
  ["topico",397,"","O primeiro pecado do homem"],
  ["topico",402,"","Consequências do pecado de Adão para a humanidade"],
  ["topico",407,"","Um duro combate"],
  ["subtitulo",410,"IV","«Vós não o abandonastes ao poder da morte»"],
  ["subtitulo",413,"","Resumindo"],
  ["capitulo",422,"Capítulo 2","Creio em Jesus Cristo, Filho único de Deus"],
  ["topico",422,"","A boa-nova: Deus enviou o seu Filho"],
  ["topico",425,"","«Anunciar a insondável riqueza de Cristo» (Ef 3, 8)"],
  ["topico",426,"","No coração da catequese: Cristo"],
  ["artigo",430,"Artigo 2","«E em Jesus Cristo, seu único Filho, nosso Senhor»","ARTIGO_2_"],
  ["subtitulo",430,"I","Jesus"],
  ["subtitulo",436,"II","Cristo"],
  ["subtitulo",441,"III","Filho único de Deus"],
  ["subtitulo",446,"IV","Senhor"],
  ["subtitulo",452,"","Resumindo"],
  ["artigo",456,"Artigo 3","«Jesus Cristo foi concebido pelo poder do Espírito Santo e nasceu da Virgem Maria»","ARTIGO_3_"],
  ["paragrafo",456,"Parágrafo 1","O Filho de Deus fez-se homem"],
  ["subtitulo",456,"I","Porque é que o Verbo encarnou?"],
  ["subtitulo",461,"II","A Encarnação"],
  ["subtitulo",464,"III","Verdadeiro Deus e verdadeiro homem"],
  ["subtitulo",470,"IV","Como é que o Filho de Deus é homem"],
  ["topico",471,"","A alma e o conhecimento humano de Cristo"],
  ["topico",475,"","A vontade humana de Cristo"],
  ["topico",476,"","O verdadeiro corpo de Cristo"],
  ["topico",478,"","O coração do Verbo encarnado"],
  ["subtitulo",479,"","Resumindo"],
  ["paragrafo",484,"Parágrafo 2","«... Concebido pelo poder do Espírito Santo, nascido da Virgem Maria»"],
  ["subtitulo",484,"I","Concebido pelo poder do Espírito Santo..."],
  ["subtitulo",487,"II","...nascido da Virgem Maria"],
  ["topico",488,"","A predestinação de Maria"],
  ["topico",490,"","A Imaculada Conceição"],
  ["topico",494,"","«Faça-se em mim segundo a tua palavra...»"],
  ["topico",495,"","A maternidade divina de Maria"],
  ["topico",496,"","A virgindade de Maria"],
  ["topico",499,"","Maria – «sempre Virgem»"],
  ["topico",502,"","A maternidade virginal de Maria no plano de Deus"],
  ["subtitulo",508,"","Resumindo"],
  ["paragrafo",512,"Parágrafo 3","Os mistérios da vida de Cristo"],
  ["subtitulo",514,"I","Toda a vida de Cristo é mistério"],
  ["topico",516,"","Os traços comuns dos mistérios de Jesus"],
  ["topico",519,"","A nossa comunhão nos mistérios de Jesus"],
  ["subtitulo",522,"II","Os mistérios da infância e da vida oculta de Jesus"],
  ["topico",522,"","Os preparativos"],
  ["topico",525,"","O mistério do Natal"],
  ["topico",527,"","Os mistérios da infância de Jesus"],
  ["topico",531,"","Os mistérios da vida oculta de Jesus"],
  ["subtitulo",535,"III","Os mistérios da vida pública de Jesus"],
  ["topico",535,"","O Baptismo de Jesus"],
  ["topico",538,"","A tentação de Jesus"],
  ["topico",541,"","«O reino de Deus está próximo»"],
  ["topico",543,"","O anúncio do reino de Deus"],
  ["topico",547,"","Os sinais do reino de Deus"],
  ["topico",551,"","«As chaves do reino»"],
  ["topico",554,"","Um antegozo do reino: a transfiguração"],
  ["topico",557,"","A subida de Jesus para Jerusalém"],
  ["topico",559,"","A entrada messiânica de Jesus em Jerusalém"],
  ["subtitulo",561,"","Resumindo"],
  ["artigo",571,"Artigo 4","«Jesus Cristo padeceu sob Pôncio Pilatos foi crucificado, morto e sepultado»","ARTIGO_4_"],
  ["paragrafo",574,"Parágrafo 1","Jesus e Israel"],
  ["subtitulo",577,"I","Jesus e a Lei"],
  ["subtitulo",583,"II","Jesus e o templo"],
  ["subtitulo",587,"III","Jesus e a fé de Israel no Deus único e salvador"],
  ["subtitulo",592,"","Resumindo"],
  ["paragrafo",595,"Parágrafo 2","Jesus morreu crucificado"],
  ["subtitulo",595,"I","O processo de Jesus"],
  ["topico",595,"","Divisões entre as autoridades judaicas a respeito de Jesus"],
  ["topico",597,"","Os judeus não são colectivamente responsáveis pela morte de Jesus"],
  ["topico",598,"","Todos os pecadores foram autores da paixão de Cristo"],
  ["subtitulo",599,"II","A morte redentora de Cristo no desígnio divino de salvação"],
  ["topico",599,"","«Jesus entregue, segundo o desígnio determinado de Deus»"],
  ["topico",601,"","«Morto pelos nossos pecados, segundo as Escrituras»"],
  ["topico",602,"","«Por nós, Deus fê-lo pecado»"],
  ["topico",604,"","Deus toma a iniciativa do amor Redentor universal"],
  ["subtitulo",606,"III","Cristo ofereceu-Se a Si mesmo ao Pai pelos nossos pecados"],
  ["topico",606,"","Toda a vida de Cristo é oblação ao Pai"],
  ["topico",608,"","«O cordeiro que tira o pecado do mundo»"],
  ["topico",609,"","Jesus partilha livremente o amor Redentor do Pai"],
  ["topico",610,"","Na ceia, Jesus antecipou a oblação livre da sua vida"],
  ["topico",612,"","A agonia no Getsémani"],
  ["topico",613,"","A morte de Cristo é o sacrifício único e definitivo"],
  ["topico",615,"","Jesus substitui a nossa desobediência pela sua obediência"],
  ["topico",616,"","Na cruz, Jesus consuma o seu sacrifício"],
  ["topico",618,"","A nossa participação no sacrifício de Cristo"],
  ["subtitulo",619,"","Resumindo"],
  ["paragrafo",624,"Parágrafo 3","Jesus Cristo foi sepultado"],
  ["topico",625,"","O corpo de Cristo no sepulcro"],
  ["topico",627,"","«Não deixareis o vosso santo sofrer a corrupção»"],
  ["topico",628,"","«Sepultados com Cristo...»"],
  ["subtitulo",629,"","Resumindo"],
  ["artigo",631,"Artigo 5","«Jesus Cristo desceu à mansão dos mortos, ao terceiro dia ressuscitou dos mortos»","ARTIGO_5_"],
  ["paragrafo",632,"Parágrafo 1","Cristo desceu à mansão dos mortos"],
  ["subtitulo",636,"","Resumindo"],
  ["paragrafo",638,"Parágrafo 2","Ao terceiro dia, ressuscitou dos mortos"],
  ["subtitulo",639,"I","Acontecimento histórico e transcendente"],
  ["topico",640,"","O túmulo vazio"],
  ["topico",641,"","As aparições do ressuscitado"],
  ["topico",645,"","O estado da humanidade ressuscitada de Cristo"],
  ["topico",647,"","A ressurreição como acontecimento transcendente"],
  ["subtitulo",648,"II","A ressurreição – obra da Santíssima Trindade"],
  ["subtitulo",651,"III","Sentido e alcance salvífico da ressurreição"],
  ["subtitulo",656,"","Resumindo"],
  ["artigo",659,"Artigo 6","«Jesus subiu aos céus e está sentado à direita de Deus, Pai Todo-Poderoso»","ARTIGO_6_"],
  ["subtitulo",665,"","Resumindo"],
  ["artigo",668,"Artigo 7","«De onde há-de vir a julgar os vivos e os mortos»","ARTIGO_7_"],
  ["subtitulo",668,"I","«Voltará na sua glória»"],
  ["topico",668,"","Cristo reina, desde já, pela Igreja..."],
  ["topico",671,"","... à espera de que tudo lhe seja submetido"],
  ["topico",673,"","A vinda gloriosa de Cristo, esperança de Israel"],
  ["topico",675,"","A última prova da Igreja"],
  ["subtitulo",678,"II","«Para julgar os vivos e os mortos»"],
  ["subtitulo",680,"","Resumindo"],
  ["capitulo",683,"Capítulo 3","Creio no Espírito Santo"],
  ["artigo",687,"Artigo 8","«Creio no Espírito Santo»","ARTIGO_8_"],
  ["subtitulo",689,"I","A missão conjunta do Filho e do Espírito"],
  ["subtitulo",691,"II","O nome, as designações e os símbolos do Espírito Santo"],
  ["topico",691,"","O nome próprio do Espírito Santo"],
  ["topico",692,"","As designações do Espírito Santo"],
  ["topico",694,"","Os símbolos do Espírito Santo"],
  ["subtitulo",702,"III","O Espírito e a Palavra de Deus, no tempo das promessas"],
  ["topico",703,"","Na criação"],
  ["topico",705,"","O Espírito da promessa"],
  ["topico",707,"","Nas teofanias e na lei"],
  ["topico",709,"","No reino e no exílio"],
  ["topico",711,"","A expectativa do Messias e do seu Espírito"],
  ["subtitulo",717,"IV","O Espírito de Cristo na plenitude do tempo"],
  ["topico",717,"","João, precursor, profeta e Baptista"],
  ["topico",721,"","«Alegra-te, ó cheia de graça»"],
  ["topico",727,"","Jesus Cristo"],
  ["subtitulo",731,"V","O Espírito e a Igreja nos últimos tempos"],
  ["topico",731,"","O Pentecostes"],
  ["topico",733,"","O Espírito Santo – dom de Deus"],
  ["topico",737,"","O Espírito Santo e a Igreja"],
  ["subtitulo",742,"","Resumindo"],
  ["artigo",748,"Artigo 9","«Creio na Santa Igreja Católica»","ARTIGO_9_"],
  ["paragrafo",751,"Parágrafo 1","A Igreja no desígnio de Deus"],
  ["subtitulo",751,"I","Os nomes e as imagens da Igreja"],
  ["topico",753,"","Os símbolos da Igreja"],
  ["subtitulo",758,"II","Origem, fundação e missão da Igreja"],
  ["topico",759,"","Um desígnio nascido no coração do Pai"],
  ["topico",760,"","A Igreja – prefigurada desde a origem do mundo"],
  ["topico",761,"","A Igreja – preparada na Antiga Aliança"],
  ["topico",763,"","A Igreja – instituída por Jesus Cristo"],
  ["topico",767,"","A Igreja – manifestada pelo Espírito Santo"],
  ["topico",769,"","A Igreja – consumada na glória"],
  ["subtitulo",770,"III","O mistério da Igreja"],
  ["topico",771,"","A Igreja – ao mesmo tempo visível e espiritual"],
  ["topico",772,"","A Igreja – mistério da união dos homens com Deus"],
  ["topico",774,"","A Igreja – sacramento universal da salvação"],
  ["subtitulo",777,"","Resumindo"],
  ["paragrafo",781,"Parágrafo 2","A Igreja – povo de Deus, corpo de Cristo, templo do Espírito Santo"],
  ["subtitulo",781,"I","A Igreja – Povo de Deus"],
  ["topico",782,"","As características do povo de Deus"],
  ["topico",783,"","Um povo sacerdotal, profético e real"],
  ["subtitulo",787,"II","A Igreja – Corpo de Cristo"],
  ["topico",787,"","A Igreja é comunhão com Jesus"],
  ["topico",790,"","«Um só corpo»"],
  ["topico",792,"","«A cabeça deste corpo é Cristo»"],
  ["topico",796,"","A Igreja é a esposa de Cristo"],
  ["subtitulo",797,"III","A Igreja – Templo do Espírito Santo"],
  ["topico",799,"","Os carismas"],
  ["subtitulo",802,"","Resumindo"],
  ["paragrafo",811,"Parágrafo 3","A Igreja é una, santa, católica e apostólica"],
  ["subtitulo",813,"I","A Igreja é una"],
  ["topico",813,"","«O sagrado mistério da unidade da Igreja»"],
  ["topico",820,"","A caminho da unidade"],
  ["subtitulo",823,"II","A Igreja é santa"],
  ["subtitulo",830,"III","A Igreja é católica"],
  ["topico",830,"","Que quer dizer «católica»?"],
  ["topico",832,"","Cada uma das Igrejas particulares é «católica»"],
  ["topico",836,"","Quem pertence à Igreja Católica?"],
  ["topico",839,"","A Igreja e os não-cristãos"],
  ["topico",846,"","«Fora da Igreja não há salvação»"],
  ["topico",849,"","A missão – uma exigência da catolicidade da Igreja"],
  ["subtitulo",857,"IV","A Igreja é apostólica"],
  ["topico",858,"","A missão dos apóstolos"],
  ["topico",861,"","Os bispos, sucessores dos apóstolos"],
  ["topico",863,"","O apostolado"],
  ["subtitulo",866,"","Resumindo"],
  ["paragrafo",871,"Parágrafo 4","Os fiéis de Cristo: hierarquia, leigos, vida consagrada"],
  ["subtitulo",874,"I","A constituição hierárquica da Igreja"],
  ["topico",874,"","Porquê o ministério eclesial?"],
  ["topico",880,"","O colégio episcopal e o seu chefe, o Papa"],
  ["topico",888,"","O ofício de ensinar"],
  ["topico",893,"","O ofício de santificar"],
  ["topico",894,"","O ofício de governar"],
  ["subtitulo",897,"II","Os fiéis leigos"],
  ["topico",898,"","A vocação dos leigos"],
  ["topico",901,"","A participação dos leigos na função sacerdotal de Cristo"],
  ["topico",904,"","A sua participação na função profética de Cristo"],
  ["topico",908,"","A sua participação na função real de Cristo"],
  ["subtitulo",914,"III","A vida consagrada"],
  ["topico",915,"","Conselhos evangélicos, vida consagrada"],
  ["topico",917,"","Uma grande árvore, de frondosa ramagem"],
  ["topico",920,"","A vida eremítica"],
  ["topico",922,"","As virgens e as viúvas consagradas"],
  ["topico",925,"","A vida religiosa"],
  ["topico",928,"","Os institutos seculares"],
  ["topico",930,"","As sociedades de vida apostólica"],
  ["topico",931,"","Consagração e missão: anunciar o rei que vem"],
  ["subtitulo",934,"","Resumindo"],
  ["paragrafo",946,"Parágrafo 5","A comunhão dos santos"],
  ["subtitulo",949,"I","A comunhão dos bens espirituais"],
  ["subtitulo",954,"II","A comunhão entre a Igreja do céu e a da terra"],
  ["subtitulo",960,"","Resumindo"],
  ["paragrafo",963,"Parágrafo 6","Maria – mãe de Cristo mãe da Igreja"],
  ["subtitulo",964,"I","A maternidade de Maria em relação à Igreja"],
  ["topico",964,"","Inteiramente unida a seu Filho..."],
  ["topico",966,"","... também na sua assunção..."],
  ["topico",967,"","... ela é nossa mãe na ordem da graça"],
  ["subtitulo",971,"II","O culto à Santíssima Virgem"],
  ["subtitulo",972,"III","Maria - ícone escatológico da Igreja"],
  ["subtitulo",973,"","Resumindo"],
  ["artigo",976,"Artigo 10","«Creio na remissão dos pecados»","ARTIGO_10_"],
  ["subtitulo",977,"I","Um só Baptismo para a remissão dos pecados"],
  ["subtitulo",981,"II","O poder das chaves"],
  ["subtitulo",984,"","Resumindo"],
  ["artigo",988,"Artigo 11","«Creio na ressurreição da carne»","ARTIGO_11_"],
  ["subtitulo",992,"I","A ressurreição de Cristo e a nossa ressurreição"],
  ["topico",992,"","Revelação progressiva da ressurreição"],
  ["topico",997,"","Como é que os mortos ressuscitam?"],
  ["topico",1002,"","Ressuscitados com Cristo"],
  ["subtitulo",1005,"II","Morrer em Cristo Jesus"],
  ["topico",1006,"","A morte"],
  ["topico",1010,"","O sentido da morte cristã"],
  ["subtitulo",1015,"","Resumindo"],
  ["artigo",1020,"Artigo 12","«Creio na vida eterna»","ARTIGO_12_"],
  ["subtitulo",1021,"I","O juízo particular"],
  ["subtitulo",1023,"II","O céu"],
  ["subtitulo",1030,"III","A purificação final ou Purgatório"],
  ["subtitulo",1033,"IV","O Inferno"],
  ["subtitulo",1038,"V","O Juízo final"],
  ["subtitulo",1042,"VI","A esperança dos novos céus e da nova terra"],
  ["subtitulo",1051,"","Resumindo"],
  ["topico",1061,"","«Amen»"],
  ["parte",1066,"Parte 2","A celebração do mistério cristão"],
  ["capitulo",1066,"","Introdução"],
  ["topico",1066,"","Porquê a liturgia?"],
  ["topico",1069,"","Qual o significado da palavra liturgia?"],
  ["topico",1071,"","A liturgia como fonte de vida"],
  ["topico",1073,"","Oração e liturgia"],
  ["topico",1074,"","Catequese e liturgia"],
  ["secao",1076,"Seção 1","A «economia» sacramental"],
  ["capitulo",1077,"Capítulo 1","O mistério pascal no tempo da Igreja"],
  ["artigo",1077,"Artigo 1","A liturgia – obra da Santíssima Trindade","ARTIGO_1_"],
  ["subtitulo",1077,"I","O Pai, fonte e fim da liturgia"],
  ["subtitulo",1084,"II","A acção de Cristo na liturgia"],
  ["topico",1084,"","Cristo glorificado..."],
  ["topico",1086,"","... desde a Igreja dos apóstolos..."],
  ["topico",1088,"","... está presente na liturgia terrestre..."],
  ["topico",1090,"","... que participa na liturgia celeste"],
  ["subtitulo",1091,"III","O Espírito Santo e a Igreja na liturgia"],
  ["topico",1093,"","O Espírito Santo prepara para acolher Cristo"],
  ["topico",1099,"","O Espírito Santo recorda o mistério de Cristo"],
  ["topico",1104,"","O Espírito Santo actualiza o mistério de Cristo"],
  ["topico",1108,"","A comunhão do Espírito Santo"],
  ["subtitulo",1110,"","Resumindo"],
  ["artigo",1113,"Artigo 2","O mistério pascal nos sacramentos da Igreja","ARTIGO_2_"],
  ["subtitulo",1114,"I","Os sacramentos de Cristo"],
  ["subtitulo",1117,"II","Os sacramentos da Igreja"],
  ["subtitulo",1122,"III","Os sacramentos da fé"],
  ["subtitulo",1127,"IV","Os sacramentos da salvação"],
  ["subtitulo",1130,"V","Os sacramentos da vida eterna"],
  ["subtitulo",1131,"","Resumindo"],
  ["capitulo",1135,"Capítulo 2","A celebração sacramental do mistério pascal"],
  ["artigo",1136,"Artigo 1","Celebrar a liturgia da Igreja","ARTIGO_1_"],
  ["subtitulo",1136,"I","Quem celebra?"],
  ["topico",1137,"","Os celebrantes da liturgia celeste"],
  ["topico",1140,"","Os celebrantes da liturgia sacramental"],
  ["subtitulo",1145,"II","Como celebrar?"],
  ["topico",1145,"","Sinais e símbolos"],
  ["topico",1153,"","Palavras e acções"],
  ["topico",1156,"","Canto e música"],
  ["topico",1159,"","As santas imagens"],
  ["subtitulo",1163,"III","Quando celebrar?"],
  ["topico",1163,"","O tempo litúrgico"],
  ["topico",1166,"","O dia do Senhor"],
  ["topico",1168,"","O ano litúrgico"],
  ["topico",1172,"","O santoral no ano litúrgico"],
  ["topico",1174,"","A liturgia das horas"],
  ["subtitulo",1179,"IV","Onde celebrar?"],
  ["subtitulo",1187,"","Resumindo"],
  ["artigo",1200,"Artigo 2","Diversidade litúrgica e unidade do mistério","ARTIGO_2_"],
  ["topico",1200,"","Tradições litúrgicas e catolicidade da Igreja"],
  ["topico",1204,"","Liturgia e culturas"],
  ["subtitulo",1207,"","Resumindo"],
  ["secao",1210,"Seção 2","Os sete sacramentos da Igreja"],
  ["capitulo",1212,"Capítulo 1","Os sacramentos da iniciação cristã"],
  ["artigo",1213,"Artigo 1","O sacramento do Baptismo","ARTIGO_1_"],
  ["subtitulo",1214,"I","Como se chama este sacramento?"],
  ["subtitulo",1217,"II","O Baptismo na economia da salvação"],
  ["topico",1217,"","As prefigurações do Baptismo na Antiga Aliança"],
  ["topico",1223,"","O Baptismo de Cristo"],
  ["topico",1226,"","O Baptismo na Igreja"],
  ["subtitulo",1229,"III","Como se celebra o sacramento do Baptismo?"],
  ["topico",1229,"","A iniciação cristã"],
  ["topico",1234,"","A mistagogia da celebração"],
  ["subtitulo",1246,"IV","Quem pode receber o Baptismo?"],
  ["topico",1247,"","O Baptismo dos adultos"],
  ["topico",1250,"","O Baptismo das crianças"],
  ["topico",1253,"","Fé e Baptismo"],
  ["subtitulo",1256,"V","Quem pode baptizar?"],
  ["subtitulo",1257,"VI","A necessidade do Baptismo"],
  ["subtitulo",1262,"VII","A graça do Baptismo"],
  ["topico",1263,"","Para a remissão dos pecados"],
  ["topico",1265,"","«Uma nova criatura»"],
  ["topico",1267,"","Incorporados na Igreja, corpo de Cristo"],
  ["topico",1271,"","O vínculo sacramental da unidade dos cristãos"],
  ["topico",1272,"","Uma marca espiritual indelével..."],
  ["subtitulo",1275,"","Resumindo"],
  ["artigo",1285,"Artigo 2","O sacramento da Confirmação","ARTIGO_2_"],
  ["subtitulo",1286,"I","A Confirmação na economia da salvação"],
  ["topico",1290,"","Duas tradições: o oriente e o ocidente"],
  ["subtitulo",1293,"II","Os sinais e o rito da Confirmação"],
  ["topico",1297,"","A celebração da Confirmação"],
  ["subtitulo",1302,"III","Os efeitos da Confirmação"],
  ["subtitulo",1306,"IV","Quem pode receber este sacramento?"],
  ["subtitulo",1312,"V","O ministro da Confirmação"],
  ["subtitulo",1315,"","Resumindo"],
  ["artigo",1322,"Artigo 3","O sacramento da Eucaristia","ARTIGO_3_"],
  ["subtitulo",1324,"I","A Eucaristia – fonte e cume da vida eclesial"],
  ["subtitulo",1328,"II","Como se chama este sacramento?"],
  ["subtitulo",1333,"III","A Eucaristia na economia da salvação"],
  ["topico",1333,"","Os sinais do pão e do vinho"],
  ["topico",1337,"","A instituição da Eucaristia"],
  ["topico",1341,"","«Fazei isto em memória de mim»"],
  ["subtitulo",1345,"IV","A celebração litúrgica da Eucaristia"],
  ["topico",1345,"","A missa de todos os séculos"],
  ["topico",1348,"","O desenrolar da celebração"],
  ["subtitulo",1356,"V","O sacrifício sacramental: acção de graças, memorial, presença"],
  ["topico",1359,"","A acção de graças e o louvor ao Pai"],
  ["topico",1362,"","O memorial sacrificial de Cristo e do seu corpo, a Igreja"],
  ["topico",1373,"","A presença de Cristo pelo poder da sua palavra e do Espírito Santo"],
  ["subtitulo",1382,"VI","O banquete pascal"],
  ["topico",1384,"","«Tomai todos e comei»: a comunhão"],
  ["topico",1391,"","Os frutos da comunhão"],
  ["subtitulo",1402,"VII","A Eucaristia – «Penhor da futura glória»"],
  ["subtitulo",1406,"","Resumindo"],
  ["capitulo",1420,"Capítulo 2","Os sacramentos de cura"],
  ["artigo",1422,"Artigo 4","O sacramento da Penitência e da Reconciliação","ARTIGO_4_"],
  ["subtitulo",1423,"I","Como se chama este sacramento?"],
  ["subtitulo",1425,"II","Porquê, um sacramento de Reconciliação depois do Baptismo?"],
  ["subtitulo",1427,"III","A conversão dos baptizados"],
  ["subtitulo",1430,"IV","A penitência interior"],
  ["subtitulo",1434,"V","As múltiplas formas da penitência na vida cristã"],
  ["subtitulo",1440,"VI","O sacramento da Penitência e da Reconciliação"],
  ["topico",1441,"","Só Deus perdoa o pecado"],
  ["topico",1443,"","Reconciliação com a Igreja"],
  ["topico",1446,"","O sacramento do perdão"],
  ["subtitulo",1450,"VII","Os actos do penitente"],
  ["topico",1451,"","A contrição"],
  ["topico",1455,"","A confissão dos pecados"],
  ["topico",1459,"","A satisfação"],
  ["subtitulo",1461,"VIII","O ministro deste sacramento"],
  ["subtitulo",1468,"IX","Os efeitos deste sacramento"],
  ["subtitulo",1471,"X","As indulgências"],
  ["topico",1472,"","O que é a indulgência?"],
  ["topico",1472,"","As penas do pecado"],
  ["topico",1474,"","Na comunhão dos santos"],
  ["topico",1478,"","Obter a indulgência de Deus mediante a Igreja"],
  ["subtitulo",1480,"XI","A celebração do sacramento da Penitência"],
  ["subtitulo",1485,"","Resumindo"],
  ["artigo",1499,"Artigo 5","A Unção dos enfermos","ARTIGO_5_"],
  ["subtitulo",1500,"I","Os seus fundamentos na economia da salvação"],
  ["topico",1500,"","A doença na vida humana"],
  ["topico",1502,"","O doente perante Deus"],
  ["topico",1503,"","Cristo-médico"],
  ["topico",1506,"","«Curai os enfermos...»"],
  ["topico",1511,"","Um sacramento dos enfermos"],
  ["subtitulo",1514,"II","Quem recebe e quem administra este sacramento?"],
  ["topico",1514,"","Em caso de grave enfermidade..."],
  ["topico",1516,"","«... Chame os presbíteros da Igreja»"],
  ["subtitulo",1517,"III","Como se celebra este sacramento?"],
  ["subtitulo",1520,"IV","Os efeitos da celebração deste sacramento"],
  ["subtitulo",1524,"V","O Viático, último sacramento do cristão"],
  ["subtitulo",1526,"","Resumindo"],
  ["capitulo",1533,"Capítulo 3","Os sacramentos ao serviço da comunhão"],
  ["artigo",1536,"Artigo 6","O sacramento da Ordem","ARTIGO_6_"],
  ["subtitulo",1537,"I","Porquê este nome de sacramento da Ordem?"],
  ["subtitulo",1539,"II","O sacramento da Ordem na economia da salvação"],
  ["topico",1539,"","O sacerdócio da Antiga Aliança"],
  ["topico",1544,"","O sacerdócio único de Cristo"],
  ["topico",1546,"","Duas participações no sacerdócio único de Cristo"],
  ["topico",1548,"","Na pessoa de Cristo cabeça..."],
  ["topico",1552,"","...«em nome de toda a Igreja»"],
  ["subtitulo",1554,"III","Os três graus do sacramento da Ordem"],
  ["topico",1555,"","A ordenação episcopal – plenitude do sacramento da Ordem"],
  ["topico",1562,"","A ordenação dos presbíteros – cooperadores dos bispos"],
  ["topico",1569,"","A ordenação do diáconos – «em vista do serviço»"],
  ["subtitulo",1572,"IV","A celebração deste sacramento"],
  ["subtitulo",1575,"V","Quem pode conferir este sacramento?"],
  ["subtitulo",1577,"VI","Quem pode receber este sacramento?"],
  ["subtitulo",1581,"VII","Os efeitos do sacramento da Ordem"],
  ["topico",1581,"","O carácter indelével"],
  ["topico",1585,"","A graça do Espírito Santo"],
  ["subtitulo",1590,"","Resumindo"],
  ["artigo",1601,"Artigo 7","O sacramento do Matrimónio","ARTIGO_7_"],
  ["subtitulo",1602,"I","O matrimónio no desígnio de Deus"],
  ["topico",1603,"","O Matrimónio na ordem da criação"],
  ["topico",1606,"","O Matrimónio sob o regime do pecado"],
  ["topico",1609,"","O Matrimónio sob a pedagogia da lei"],
  ["topico",1612,"","O Matrimónio no Senhor"],
  ["topico",1618,"","A virgindade por amor do reino"],
  ["subtitulo",1621,"II","A celebração do Matrimónio"],
  ["subtitulo",1625,"III","O consentimento matrimonial"],
  ["topico",1633,"","Casamentos mistos e disparidade de cultos"],
  ["subtitulo",1638,"IV","Os efeitos do sacramento do Matrimónio"],
  ["topico",1639,"","O vínculo matrimonial"],
  ["topico",1641,"","A graça do sacramento do Matrimónio"],
  ["subtitulo",1643,"V","Os bens e as exigências do amor conjugal"],
  ["topico",1644,"","A unidade e a indissolubilidade do Matrimónio"],
  ["topico",1646,"","A fidelidade do amor conjugal"],
  ["topico",1652,"","A abertura à fecundidade"],
  ["subtitulo",1655,"VI","A Igreja doméstica"],
  ["subtitulo",1659,"","Resumindo"],
  ["capitulo",1667,"Capítulo 4","As outras celebrações litúrgicas"],
  ["artigo",1667,"Artigo 1","Os sacramentais","ARTIGO_1_"],
  ["topico",1668,"","Traços característicos dos sacramentais"],
  ["topico",1671,"","Formas variadas dos sacramentais"],
  ["topico",1674,"","A religiosidade popular"],
  ["subtitulo",1677,"","Resumindo"],
  ["artigo",1680,"Artigo 2","As exéquias cristãs","ARTIGO_2_"],
  ["subtitulo",1681,"I","A última Páscoa do cristão"],
  ["subtitulo",1684,"II","A celebração das exéquias"],
  ["parte",1691,"Parte 3","A vida em Cristo"],
  ["capitulo",1691,"","Introdução"],
  ["secao",1699,"Seção 1","A vocação do homem: a vida no Espírito"],
  ["capitulo",1700,"Capítulo 1","A dignidade da pessoa humana"],
  ["artigo",1701,"Artigo 1","O homem, imagem de Deus","ARTIGO_1_"],
  ["subtitulo",1710,"","Resumindo"],
  ["artigo",1716,"Artigo 2","A nossa vocação para a bem-aventurança","ARTIGO_2_"],
  ["subtitulo",1716,"I","As bem-aventuranças"],
  ["subtitulo",1718,"II","O desejo de felicidade"],
  ["subtitulo",1720,"III","A bem-aventurança cristã"],
  ["subtitulo",1725,"","Resumindo"],
  ["artigo",1730,"Artigo 3","A liberdade do homem","ARTIGO_3_"],
  ["subtitulo",1731,"I","Liberdade e responsabilidade"],
  ["subtitulo",1739,"II","A liberdade humana na economia da salvação"],
  ["subtitulo",1743,"","Resumindo"],
  ["artigo",1749,"Artigo 4","A moralidade dos actos humanos","ARTIGO_4_"],
  ["subtitulo",1750,"I","As fontes da moralidade"],
  ["subtitulo",1755,"II","Os actos bons e os actos maus"],
  ["subtitulo",1757,"","Resumindo"],
  ["artigo",1762,"Artigo 5","A moralidade das paixões","ARTIGO_5_"],
  ["subtitulo",1763,"I","As paixões"],
  ["subtitulo",1767,"II","Paixões e vida moral"],
  ["subtitulo",1771,"","Resumindo"],
  ["artigo",1776,"Artigo 6","A consciência moral","ARTIGO_6_"],
  ["subtitulo",1777,"I","O juízo da consciência"],
  ["subtitulo",1783,"II","A formação da consciência"],
  ["subtitulo",1786,"III","Decidir em consciência"],
  ["subtitulo",1790,"IV","O juízo erróneo"],
  ["subtitulo",1795,"","Resumindo"],
  ["artigo",1803,"Artigo 7","As virtudes","ARTIGO_7_"],
  ["subtitulo",1804,"I","As virtudes humanas"],
  ["topico",1805,"","Distinção das virtudes cardeais"],
  ["topico",1810,"","As virtudes e a graça"],
  ["subtitulo",1812,"II","As virtudes teologais"],
  ["topico",1814,"","A fé"],
  ["topico",1817,"","A esperança"],
  ["topico",1822,"","A caridade"],
  ["subtitulo",1830,"III","Os dons e os frutos do Espírito Santo"],
  ["subtitulo",1833,"","Resumindo"],
  ["artigo",1846,"Artigo 8","O pecado","ARTIGO_8_"],
  ["subtitulo",1846,"I","A misericórdia e o pecado"],
  ["subtitulo",1849,"II","Definição de pecado"],
  ["subtitulo",1852,"III","A diversidade dos pecados"],
  ["subtitulo",1854,"IV","A gravidade do pecado: pecado mortal e pecado venial"],
  ["subtitulo",1865,"V","A proliferação do pecado"],
  ["subtitulo",1870,"","Resumindo"],
  ["capitulo",1877,"Capítulo 2","A comunidade humana"],
  ["artigo",1878,"Artigo 1","A pessoa e a sociedade","ARTIGO_1_"],
  ["subtitulo",1878,"I","O carácter comunitário da vocação humana"],
  ["subtitulo",1886,"II","Conversão e sociedade"],
  ["subtitulo",1890,"","Resumindo"],
  ["artigo",1897,"Artigo 2","A participação na vida social","ARTIGO_2_"],
  ["subtitulo",1897,"I","A autoridade"],
  ["subtitulo",1905,"II","O bem comum"],
  ["subtitulo",1913,"III","Responsabilidade e participação"],
  ["subtitulo",1918,"","Resumindo"],
  ["artigo",1928,"Artigo 3","A justiça social","ARTIGO_3_"],
  ["subtitulo",1929,"I","O respeito pela pessoa humana"],
  ["subtitulo",1934,"II","Igualdade e diferença entre os homens"],
  ["subtitulo",1939,"III","A solidariedade humana"],
  ["subtitulo",1943,"","Resumindo"],
  ["capitulo",1949,"Capítulo 3","A salvação de Deus: a lei e a graça"],
  ["artigo",1950,"Artigo 1","A lei moral","ARTIGO_1_"],
  ["subtitulo",1954,"I","A lei moral natural"],
  ["subtitulo",1961,"II","A Lei antiga"],
  ["subtitulo",1965,"III","A nova Lei ou Lei evangélica"],
  ["subtitulo",1975,"","Resumindo"],
  ["artigo",1987,"Artigo 2","Graça e justificação","ARTIGO_2_"],
  ["subtitulo",1987,"I","A justificação"],
  ["subtitulo",1996,"II","A graça"],
  ["subtitulo",2006,"III","O mérito"],
  ["subtitulo",2012,"IV","A santidade cristã"],
  ["subtitulo",2017,"","Resumindo"],
  ["artigo",2030,"Artigo 3","A Igreja, mãe e educadora","ARTIGO_3_"],
  ["subtitulo",2032,"I","Vida moral e Magistério da Igreja"],
  ["subtitulo",2041,"II","Os preceitos da Igreja"],
  ["subtitulo",2044,"III","Vida moral e testemunho missionário"],
  ["subtitulo",2047,"","Resumindo"],
  ["secao",2052,"Seção 2","Os dez mandamentos"],
  ["topico",2052,"","«Mestre, que hei-de fazer...?»"],
  ["topico",2056,"","O Decálogo na Sagrada Escritura"],
  ["topico",2064,"","O Decálogo na tradição da Igreja"],
  ["topico",2069,"","A unidade do Decálogo"],
  ["topico",2070,"","O Decálogo e a lei natural"],
  ["topico",2072,"","A obrigação do Decálogo"],
  ["topico",2074,"","«Sem mim, nada podeis fazer»"],
  ["subtitulo",2075,"","Resumindo"],
  ["capitulo",2083,"Capítulo 1","«Amarás o Senhor teu Deus com todo o teu coração, com toda a tua alma e com todas as tuas forças»"],
  ["artigo",2084,"Artigo 1","O primeiro mandamento","ARTIGO_1_"],
  ["subtitulo",2084,"I","«Ao Senhor teu Deus adorarás, a Ele servirás»"],
  ["topico",2087,"","A fé"],
  ["topico",2090,"","A esperança"],
  ["topico",2093,"","A caridade"],
  ["subtitulo",2095,"II","«Só a Ele prestarás culto»"],
  ["topico",2096,"","A adoração"],
  ["topico",2098,"","A oração"],
  ["topico",2099,"","O sacrifício"],
  ["topico",2101,"","Promessas e votos"],
  ["topico",2104,"","O dever social de religião e o direito à liberdade religiosa"],
  ["subtitulo",2110,"III","«Não terás outros deuses perante Mim»"],
  ["topico",2111,"","A superstição"],
  ["topico",2112,"","A idolatria"],
  ["topico",2115,"","Adivinhação e magia"],
  ["topico",2118,"","A irreligião"],
  ["topico",2123,"","O ateísmo"],
  ["topico",2127,"","O agnosticismo"],
  ["subtitulo",2129,"IV","«Não farás para ti nenhuma imagem esculpida...»"],
  ["subtitulo",2133,"","Resumindo"],
  ["artigo",2142,"Artigo 2","O segundo mandamento","ARTIGO_2_"],
  ["subtitulo",2142,"I","O nome do Senhor é Santo"],
  ["subtitulo",2150,"II","O nome do Senhor invocado em vão"],
  ["subtitulo",2156,"III","O nome cristão"],
  ["subtitulo",2160,"","Resumindo"],
  ["artigo",2168,"Artigo 3","O terceiro mandamento","ARTIGO_3_"],
  ["subtitulo",2168,"I","O dia do sábado"],
  ["subtitulo",2174,"II","O dia do Senhor"],
  ["topico",2174,"","O dia da ressurreição: a nova criação"],
  ["topico",2175,"","O domingo – realização do sábado"],
  ["topico",2177,"","A Eucaristia dominical"],
  ["topico",2180,"","A obrigação do domingo"],
  ["topico",2184,"","Dia de graça e de cessação do trabalho"],
  ["subtitulo",2189,"","Resumindo"],
  ["capitulo",2196,"Capítulo 2","«Amarás o teu próximo como a ti mesmo»"],
  ["artigo",2197,"Artigo 4","O quarto mandamento","ARTIGO_4_"],
  ["subtitulo",2201,"I","A família no plano de Deus"],
  ["topico",2201,"","Natureza da família"],
  ["topico",2204,"","A família cristã"],
  ["subtitulo",2207,"II","A família e a sociedade"],
  ["subtitulo",2214,"III","Deveres dos membros da família"],
  ["topico",2214,"","Deveres dos filhos"],
  ["topico",2221,"","Deveres dos pais"],
  ["subtitulo",2232,"IV","A família e o Reino"],
  ["subtitulo",2234,"V","As autoridades na sociedade civil"],
  ["topico",2235,"","Deveres das autoridades civis"],
  ["topico",2238,"","Deveres dos cidadãos"],
  ["topico",2244,"","A comunidade política e a Igreja"],
  ["subtitulo",2247,"","Resumindo"],
  ["artigo",2258,"Artigo 5","O quinto mandamento","ARTIGO_5_"],
  ["subtitulo",2259,"I","O respeito pela vida humana"],
  ["topico",2259,"","Testemunho da história sagrada"],
  ["topico",2263,"","A legítima defesa"],
  ["topico",2268,"","O homicídio voluntário"],
  ["topico",2270,"","O aborto"],
  ["topico",2276,"","A eutanásia"],
  ["topico",2280,"","O suicídio"],
  ["subtitulo",2284,"II","O respeito pela dignidade das pessoas"],
  ["topico",2284,"","O respeito pela alma do próximo: o escândalo"],
  ["topico",2288,"","O respeito pela saúde"],
  ["topico",2292,"","O respeito pela pessoa e a investigação científica"],
  ["topico",2297,"","O respeito pela integridade corporal"],
  ["topico",2299,"","O respeito pelos mortos"],
  ["topico",2302,"","A salvaguarda da paz"],
  ["topico",2302,"","A paz"],
  ["topico",2307,"","Evitar a guerra"],
  ["subtitulo",2318,"","Resumindo"],
  ["artigo",2331,"Artigo 6","O sexto mandamento","ARTIGO_6_"],
  ["subtitulo",2331,"I","«Homem e mulher os criou»..."],
  ["subtitulo",2337,"II","A vocação à castidade"],
  ["topico",2338,"","A integridade da pessoa"],
  ["topico",2346,"","A integralidade do dom de si"],
  ["topico",2348,"","Os diversos regimes da castidade"],
  ["topico",2351,"","As ofensas à castidade"],
  ["topico",2357,"","Castidade e homossexualidade"],
  ["subtitulo",2360,"III","O amor dos esposos"],
  ["topico",2364,"","A fidelidade conjugal"],
  ["topico",2366,"","A fecundidade do Matrimónio"],
  ["topico",2373,"","O dom do Filho"],
  ["subtitulo",2380,"IV","As ofensas à dignidade do matrimónio"],
  ["topico",2382,"","O divórcio"],
  ["topico",2387,"","Outras ofensas à dignidade do Matrimónio"],
  ["subtitulo",2392,"","Resumindo"],
  ["artigo",2401,"Artigo 7","O sétimo mandamento","ARTIGO_7_"],
  ["subtitulo",2402,"I","O destino universal e a propriedade privada dos bens"],
  ["subtitulo",2407,"II","O respeito pelas pessoas e seus bens"],
  ["topico",2408,"","O respeito pelos bens alheios"],
  ["topico",2415,"","O respeito pela integridade da criação"],
  ["subtitulo",2419,"III","A doutrina social da Igreja"],
  ["subtitulo",2426,"IV","A actividade económica e a justiça social"],
  ["subtitulo",2437,"V","Justiça e solidariedade entre as nações"],
  ["subtitulo",2443,"VI","O amor dos pobres"],
  ["subtitulo",2450,"","Resumindo"],
  ["artigo",2464,"Artigo 8","O oitavo mandamento","ARTIGO_8_"],
  ["subtitulo",2465,"I","Viver na verdade"],
  ["subtitulo",2471,"II","«Dar testemunho da verdade»"],
  ["subtitulo",2475,"III","As ofensas à verdade"],
  ["subtitulo",2488,"IV","O respeito pela verdade"],
  ["subtitulo",2493,"V","O uso dos meios de comunicação social"],
  ["subtitulo",2500,"VI","Verdade, beleza e arte sacra"],
  ["subtitulo",2504,"","Resumindo"],
  ["artigo",2514,"Artigo 9","O nono mandamento","ARTIGO_9_"],
  ["subtitulo",2517,"I","A purificação do coração"],
  ["subtitulo",2520,"II","O combate pela pureza"],
  ["subtitulo",2528,"","Resumindo"],
  ["artigo",2534,"Artigo 10","O décimo mandamento","ARTIGO_10_"],
  ["subtitulo",2535,"I","A desordem das cobiças"],
  ["subtitulo",2541,"II","Os desejos do Espírito"],
  ["subtitulo",2544,"III","A pobreza de coração"],
  ["subtitulo",2548,"IV","«Quero ver a Deus»"],
  ["subtitulo",2551,"","Resumindo"],
  ["parte",2558,"Parte 4","A oração cristã"],
  ["secao",2558,"Seção 1","A oração na vida cristã"],
  ["topico",2559,"","O que é a oração?"],
  ["topico",2559,"","A oração como dom de Deus"],
  ["topico",2562,"","A oração como aliança"],
  ["topico",2565,"","A oração como comunhão"],
  ["capitulo",2566,"Capítulo 1","A revelação da oração"],
  ["topico",2566,"","O apelo universal à oração"],
  ["artigo",2568,"Artigo 1","No Antigo Testamento","ARTIGO_1_"],
  ["topico",2569,"","A criação – fonte da oração"],
  ["topico",2570,"","A promessa e a oração da fé"],
  ["topico",2574,"","Moisés e a oração do Mediador"],
  ["topico",2578,"","David e a oração do rei"],
  ["topico",2581,"","Elias, os profetas e a conversão do coração"],
  ["topico",2585,"","Os salmos, oração da assembleia"],
  ["subtitulo",2590,"","Resumindo"],
  ["artigo",2598,"Artigo 2","Na plenitude do tempo","ARTIGO_2_"],
  ["topico",2599,"","Jesus ora"],
  ["topico",2607,"","Jesus ensina a orar"],
  ["topico",2616,"","Jesus atende a oração"],
  ["topico",2617,"","A oração da Virgem Maria"],
  ["subtitulo",2620,"","Resumindo"],
  ["artigo",2623,"Artigo 3","No tempo da Igreja","ARTIGO_3_"],
  ["subtitulo",2626,"I","A bênção e a adoração"],
  ["subtitulo",2629,"II","A oração de petição"],
  ["subtitulo",2634,"III","A oração de intercessão"],
  ["subtitulo",2637,"IV","A oração de acção de graças"],
  ["subtitulo",2639,"V","A oração de louvor"],
  ["subtitulo",2644,"","Resumindo"],
  ["capitulo",2650,"Capítulo 2","A tradição da oração"],
  ["artigo",2652,"Artigo 1","Nas fontes da oração","ARTIGO_1_"],
  ["topico",2653,"","A palavra de Deus"],
  ["topico",2655,"","A liturgia da Igreja"],
  ["topico",2656,"","As virtudes teologais"],
  ["topico",2659,"","«Hoje»"],
  ["subtitulo",2661,"","Resumindo"],
  ["artigo",2663,"Artigo 2","O caminho da oração","ARTIGO_2_"],
  ["topico",2664,"","A oração ao Pai"],
  ["topico",2665,"","A oração a Jesus"],
  ["topico",2670,"","«Vinde, Espírito Santo»"],
  ["topico",2673,"","Em comunhão com a santa mãe de Deus"],
  ["subtitulo",2680,"","Resumindo"],
  ["artigo",2683,"Artigo 3","Guias para a oração","ARTIGO_3_"],
  ["topico",2683,"","Uma nuvem de testemunhas"],
  ["topico",2685,"","Servos da oração"],
  ["topico",2691,"","Lugares favoráveis à oração"],
  ["subtitulo",2692,"","Resumindo"],
  ["capitulo",2697,"Capítulo 3","A vida de oração"],
  ["artigo",2700,"Artigo 1","As expressões da oração","ARTIGO_1_"],
  ["subtitulo",2700,"I","A oração vocal"],
  ["subtitulo",2705,"II","A meditação"],
  ["subtitulo",2709,"III","A contemplação"],
  ["subtitulo",2720,"","Resumindo"],
  ["artigo",2725,"Artigo 2","O combate da oração","ARTIGO_2_"],
  ["subtitulo",2726,"I","As objecções à oração"],
  ["subtitulo",2729,"II","A humilde vigilância do coração"],
  ["topico",2729,"","Perante as dificuldades da oração"],
  ["topico",2732,"","Perante as tentações na oração"],
  ["subtitulo",2734,"III","A confiança filial"],
  ["topico",2735,"","Porque nos lamentarmos por não sermos atendidos?"],
  ["topico",2738,"","Como é que a nossa oração seria eficaz?"],
  ["subtitulo",2742,"IV","Perseverar no amor"],
  ["subtitulo",2746,"V","A oração da Hora de Jesus"],
  ["subtitulo",2752,"","Resumindo"],
  ["secao",2759,"Seção 2","A oração do Senhor: «Pai Nosso»"],
  ["artigo",2761,"Artigo 1","«O resumo de todo o Evangelho»","ARTIGO_1_"],
  ["subtitulo",2762,"I","No centro da Sagrada Escritura"],
  ["subtitulo",2765,"II","«A oração do Senhor»"],
  ["subtitulo",2767,"III","A oração da Igreja"],
  ["subtitulo",2773,"","Resumindo"],
  ["artigo",2777,"Artigo 2","«Pai Nosso, que estais nos céus»","ARTIGO_2_"],
  ["subtitulo",2777,"I","«Ousar aproximar-se com toda a confiança»"],
  ["subtitulo",2779,"II","«Pai!»"],
  ["subtitulo",2786,"III","Pai «nosso»"],
  ["subtitulo",2794,"IV","«Que estais nos céus»"],
  ["subtitulo",2797,"","Resumindo"],
  ["artigo",2803,"Artigo 3","As sete petições","ARTIGO_3_"],
  ["subtitulo",2807,"I","«Santificado seja o vosso nome»"],
  ["subtitulo",2816,"II","«Venha a nós o vosso Reino»"],
  ["subtitulo",2822,"III","«Seja feita a vossa vontade assim na terra como no céu»"],
  ["subtitulo",2828,"IV","«O pão nosso de cada dia nos dai hoje»"],
  ["subtitulo",2838,"V","«Perdoai-nos as nossas ofensas assim como nós perdoamos a quem nos tem ofendido»"],
  ["topico",2839,"","«Perdoai-nos as nossas ofensas»..."],
  ["topico",2842,"","«Assim como nós perdoamos a quem nos tem ofendido»"],
  ["subtitulo",2846,"VI","«Não nos deixeis cair em tentação»"],
  ["subtitulo",2850,"VII","«Mas livrai-nos do Mal»"],
  ["topico",2855,"","A doxologia final"],
  ["subtitulo",2857,"","Resumindo"],
];
